<?php

namespace BlogBundle\Repository\Blog;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends \Doctrine\ORM\EntityRepository
{

    public function getLatestNews()
    {

        $qb = $this->createQueryBuilder('p')
            ->orderBy('p.id', 'DESC')
            ->setMaxResults( 3 )
            ->getQuery();

        return $qb->execute();

    }
}
