slider:
  resource: "@SliderBundle/Controller/"
  type:     annotation
  prefix:   /admin



slider.api:
  resource: SliderBundle\Controller\SliderApiController
  type: rest
  prefix: /api/


slider_post:
  path: /api/slider/add
  methods: [POST]
  defaults:
    _controller: SliderBundle:SliderApi:postSlider #here is the path to controller action
    _format: json

#slider_delete:
#    path: /api/slider/delete/{sliderId}
#    methods: [DELETE]
#    defaults:
#        _controller: SliderBundle:SliderApi:deleteSlider #here is the path to controller action
#        _format: json

patch_slider_test:
  path: /api/slider/{slider}/edit
  methods: [PATCH]
  defaults:
    _controller: SliderBundle:SliderApi:patchSlider
    _format: json

